node:
  # legend:
  # C = Configurable
  # H = Hard-coded, non-configurable
  type: water-level-sensor-simulator # [H]
  name: well-water-upper-level-sensor-simulator # [C]
  logLevel: debug # [C]
  logFormat: text # [C]
  configFileName: config.yml # [C]
  ports:
    configure: # [H]
      extend: false # Add new I/O port
      modify: true # Change I/O port's public properties
    inputs: # [C]
      - name: reference-water-level
        type: base/Float64
        representation: application/json
        channel: "" # Use the default value only
        default: '{ "Body": { "Data": 0.75 } }'
      - name: water-level
        type: base/Float64
        representation: application/json
        channel: well-water-level
        default: '{ "Body": { "Data": 0.0 } }'
    outputs: # [C]
      - name: water-level-state
        type: base/Bool
        representation: application/json
        channel: well-water-upper-level-state
  orchestration: # [C]
    presence: true # Use the presence channels, must be `true` if `synchronization` is enabled
    synchronization: true # The processing and message passing is synchronized by the orchestrator
    statusRequest: status-request
    statusReport: status-report
    sendResults: send-results
    sendingCompleted: sending-completed
    receiveAndProcess: receive-and-process
    processingCompleted: processing-completed
    channels:
      statusRequest: status-request
      statusReport: status-report
      sendResults: send-results
      sendingCompleted: sending-completed
      receiveAndProcess: receive-and-process
      processingCompleted: processing-completed
  messenger: # [C]
    urls: "localhost:4222"
    credentials: ""
extDescription: This is an extensional property
