agentType: water-level-sensor-simulator
agentName: well-water-upper-level-sensor-simulator 
io:
  configuration:
    extend: false # Add new I/O port
    overwrite: false # Change any I/O port's property
    configure: true # Change only the channels, and default values
  inputs:
    - name: reference-water-level
      type: base/Float64
      representation: application/json
      channel: "" # Use the default value only
      default: '{ "Body": { "Data": 0.75 } }'
    - name: water-level
      type: base/Float64
      representation: application/json
      channel: well-water-level
      default: '{ "Body": { "Data": 0.0 } }'
  outputs:
    - name: water-level-state
      type: base/Bool
      representation: application/json
      channel: well-water-upper-level-state
orchestration:
  presence: true # Use the presence channels, must be `true` if `synchronization` is enabled
  synchronization: true # The processing and message passing is synchronized by the orchestrator
  statusRequest: status-request
  statusReport: status-report
  sendResults: send-results
  sendingCompleted: sending-completed
  receiveAndProcess: receive-and-process
  processingCompleted: processing-completed
messenger:
  urls: "localhost:4222"
  credentials: ""

