heartbeat: 1000000000
maxResponseTime: 1500000000
epnStatusChannel: epn-status
name: axon-orchestrator
logLevel: debug
logFormat: text
configFileName: config.yml
orchestration:
  presence: true # Use the presence channels, must be `true` if `synchronization` is enabled
  synchronization: false # The processing and message passing is NOT synchronized by the orchestrator
  channels:
    statusRequest: status-request
    statusReport: status-report
    sendResults: send-results
    sendingCompleted: sending-completed
    receiveAndProcess: receive-and-process
    processingCompleted: processing-completed
messenger:
  urls: "localhost:4222"
  credentials: ""
  clusterID: ""
