node:
  # legend:
  # C = Configurable
  # H = Hard-coded, non-configurable
  name: axon-cron # [C]
  logLevel: debug # [C]
  logFormat: json # [C]
  configFileName: config.yml # [C]
  ports:
    configure: # [H]
      extend: false # Can NOT add new I/O port
      modify: true # Can configure the existing I/O port parameters
    inputs: [] # No inputs
    outputs: # [C]
      - name: cron
        type: base/Any
        representation: application/json
        channel: axon.cron
  orchestration: # [C]
    presence: true # Use the presence channels, must be `true` if `synchronization` is enabled
    synchronization: false # The processing and message passing is NOT synchronized by the orchestrator
    statusRequest: status-request
    statusReport: status-report
  messenger:
    urls: "localhost:4222"
    credentials: ""
