cronDef: "@every 20s"
precision: ms
node:
  name: axon-cron
  logLevel: debug
  logFormat: json
  configFileName: config.yml
  ports:
    configure:
      extend: false # Can NOT add new I/O port
      modify: true # Can configure the existing I/O port parameters
    inputs:
      - name: trigger
        type: base/Bool
        representation: application/json
        channel: axon.cron.trigger
    outputs:
      - name: cron
        type: base/Any
        representation: application/json
        channel: axon.cron
  orchestration:
    presence: true # Use the presence channels, must be `true` if `synchronization` is enabled
    synchronization: false # The processing and message passing is NOT synchronized by the orchestrator
    statusRequest: status-request
    statusReport: status-report
  messenger:
    urls: "localhost:4222"
    credentials: ""
